[book]
title = "Audius Yellowpaper"
author = "Alec Savoy"

[output.html]
default-theme = "auto"
mathjax-support = true
additional-js = ["./js/mermaid.min.js", "./js/mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
