[book]
title = "Audius Yellowpaper"
authors = ["Alec Savoy"]
description = "the implementation of the audius mainnet"
language = "en"
text-direction = "ltr"

[output.html]
default-theme = "audius-light"
preferred-dark-theme = "audius-dark"
mathjax-support = true
additional-js = ["./js/mermaid.min.js", "./js/mermaid-init.js"]

[output.html.search]
enable = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
